namespace GenshinCBTServer.Data;
public enum EquipType
{
    EQUIP_NONE = 0,
    EQUIP_BRACER = 1,
    EQUIP_DRESS = 2,
    EQUIP_SHOES = 3,
    EQUIP_RING = 4,
    EQUIP_NECKLACE = 5,
    EQUIP_WEAPON = 6
}
public enum QuestState
{
    NONE = 0,
    UNSTARTED = 1,
    UNFINISHED = 2,
    FINISHED = 3,
    FAILED = 4,
}
public enum ParentQuestState
{
    PARENT_QUEST_STATE_NONE = 0,
    PARENT_QUEST_STATE_FINISHED = 1,
    PARENT_QUEST_STATE_FAILED = 2,
    PARENT_QUEST_STATE_CANCELED = 3
}
public enum WeaponType
{
    WEAPON_NONE = 0,
    WEAPON_SWORD_ONE_HAND = 1,
    WEAPON_CROSSBOW = 2,
    WEAPON_STAFF = 3,
    WEAPON_DOUBLE_DAGGER = 4,
    WEAPON_KATANA = 5,
    WEAPON_SHURIKEN = 6,
    WEAPON_STICK = 7,
    WEAPON_SPEAR = 8,
    WEAPON_SHIELD_SMALL = 9,
    WEAPON_CATALYST = 10,
    WEAPON_CLAYMORE = 11,
    WEAPON_BOW = 12,
    WEAPON_POLE = 13
}

public enum ItemType
{
    ITEM_NONE = 0,
    ITEM_VIRTUAL = 1,
    ITEM_MATERIAL = 2,
    ITEM_RELIQUARY = 3,
    ITEM_WEAPON = 4
}

public enum ArithType
{
    ARITH_NONE = 0,
    ARITH_ADD = 1,
    ARITH_MULTI = 2,
    ARITH_SUB = 3,
    ARITH_DIVIDE = 4,
}

public enum GrowCurveType
{
    GROW_CURVE_NONE = 0,
    GROW_CURVE_HP = 1,
    GROW_CURVE_ATTACK = 2,
    GROW_CURVE_STAMINA = 3,
    GROW_CURVE_STRIKE = 4,
    GROW_CURVE_ANTI_STRIKE = 5,
    GROW_CURVE_ANTI_STRIKE1 = 6,
    GROW_CURVE_ANTI_STRIKE2 = 7,
    GROW_CURVE_ANTI_STRIKE3 = 8,
    GROW_CURVE_STRIKE_HURT = 9,
    GROW_CURVE_ELEMENT = 10,
    GROW_CURVE_KILL_EXP = 11,
    GROW_CURVE_DEFENSE = 12,
    GROW_CURVE_ATTACK_BOMB = 13,
    GROW_CURVE_HP_LITTLEMONSTER = 14,
    GROW_CURVE_HP_S5 = 21,
    GROW_CURVE_HP_S4 = 22,
    GROW_CURVE_ATTACK_S5 = 31,
    GROW_CURVE_ATTACK_S4 = 32,
    GROW_CURVE_ATTACK_S3 = 33,
    GROW_CURVE_DEFENSE_S5 = 41,
    GROW_CURVE_DEFENSE_S4 = 42,
}

public enum ElementType
{
    None = 0,
    Fire = 1,
    Water = 2,
    Grass = 3,
    Electric = 4,
    Ice = 5,
    Frozen = 6,
    Wind = 7,
    Rock = 8,
    AntiFire = 9,
}

public enum CompoundType
{
    COMPOUND_NONE = 0,
    COMPOUND_COOK = 1,
    COMPOUND_PLACEHOLDER_2 = 2,
}

public enum ItemUseOp
{
    ITEM_USE_NONE = 0,
    ITEM_USE_ACCEPT_QUEST = 1,
    ITEM_USE_TRIGGER_ABILITY = 2,
    ITEM_USE_GAIN_AVATAR = 3,
    ITEM_USE_ADD_EXP = 4,
    ITEM_USE_RELIVE_AVATAR = 5,
    ITEM_USE_ADD_BIG_TALENT_POINT = 6,
    ITEM_USE_ADD_PERSIST_STAMINA = 7,
    ITEM_USE_ADD_TEMPORARY_STAMINA = 8,
    ITEM_USE_ADD_CUR_STAMINA = 9,
    ITEM_USE_ADD_CUR_HP = 10,
    ITEM_USE_ADD_ELEM_ENERGY = 11,
    ITEM_USE_ADD_ALL_ENERGY = 12,
    ITEM_USE_ADD_DUNGEON_COND_TIME = 13,
    ITEM_USE_ADD_WEAPON_EXP = 14,
    ITEM_USE_ADD_SERVER_BUFF = 15,
    ITEM_USE_DEL_SERVER_BUFF = 16,
    ITEM_USE_UNLOCK_COOK_RECIPE = 17,
    ITEM_USE_ADD_AVATAR_BIG_TALENT_POINT = 18,
    ITEM_USE_ADD_AVATAR_SMALL_TALENT_POINT = 19,
    ITEM_USE_OPEN_RANDOM_CHEST = 20,
    ITEM_USE_OPEN_CHEST = 21,
    ITEM_USE_ADD_MAIN_AVATAR_BIG_TALENT_POINT = 22,
    ITEM_USE_ADD_MAIN_AVATAR_SMALL_TALENT_POINT = 23
}
public enum ItemUseTarget
{
    ITEM_USE_TARGET_NONE = 0,
    ITEM_USE_TARGET_CUR_AVATAR = 1,
    ITEM_USE_TARGET_CUR_TEAM = 2,
    ITEM_USE_TARGET_SPECIFY_AVATAR = 3,
    ITEM_USE_TARGET_SPECIFY_ALIVE_AVATAR = 4,
    ITEM_USE_TARGET_SPECIFY_DEAD_AVATAR = 5,
}